### ISSUE TITLE
Does not display correctly when screen rotated

### ISSUE THREAD

**Issue by lloyda** [aukedejong/lovelace-windrose-card#10]
One small problem is that if I rotate my phone, I have to refresh the screen to get the rose to display correctly. I don't have to do this with any other gauges.

**Comment by lloyda** [comment]
Three screenshots below - portrait, landscape and landscape after refresh.

And here is the config:

```
      - type: custom:windrose-card
        title:
        max_width: 400
        hours_to_show: 4
        windspeed_bar_full: true
        wind_direction_entity: sensor.wind_direction
        windspeed_bar_location: bottom
        direction_speed_time_diff: 600
        matching_strategy: speed-first
        windspeed_entities:
          - entity: sensor.wind_speed
            name: " "
        input_speed_unit: kph
        output_speed_unit: kph
        speed_ranges:
          - from_value: 0
            color: rgba(230, 247, 255, 0.7)
          - from_value: 3
            color: rgba(129, 204, 255, 0.7)
          - from_value: 5
            color: rgba(3, 169, 244, 0.7)
          - from_value: 10
            color: rgba(2, 104, 151, 0.7)
          - from_value: 20
            color: rgba(1, 35, 50, 0.7)
        view_layout:
          grid-area: stats1
```

![Screenshot_20230320-175317](https://user-images.githubusercontent.com/1671197/226433516-cc08d1e9-717f-4b32-b5ba-13fd854998e0.png)
![Screenshot_20230320-175334](https://user-images.githubusercontent.com/1671197/226433557-72521bb8-60ec-4f63-9e1d-a3e1d7ec7935.png)
![Screenshot_20230320-175342](https://user-images.githubusercontent.com/1671197/226434022-f4a18306-78a0-4ed5-88dc-e1cfd6edcf53.png)
