### ISSUE TITLE
[Feature Request] Add speed_unit to corner_info and then follow output_speed_unit for display

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#103]
My weather station provides all speed as kph. Currently the wind speed entities have a speed_unit and then output using the output_speed_unit to allow a conversion. It would be great if the corner_info could have the same capability. So supply both a speed_unit and an output_speed_unit and remove the current unit. e.g.

```
corner_info:
  top_left:
    label: Current windspeed
    speed_unit: kph
    output_speed_unit: mph
    entity: sensor.wind_speed
  bottom_left:
    label: Gust windspeed
    speed_unit: kph
    output_speed_unit: mph
    entity: sensor.wind_gust_speed
```
