### ISSUE TITLE
dynamic wind speed doesn't work for me

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#107]
Thanks for implementing the new features. 

First there's a typo in the Object dynamic_speed_ranges table showing "below_average" key rather than the correct "average_below"

Unfortunately I can't make it work as it raises an error in the console.

`[Error] card – "custom:windrose-card" – Error: Dynamic speed ranges average_below should be a number higher then 0.`

Config is as follows.

```
windspeed_entities:
  - entity: sensor.wind_speed
    name: speed
    speed_unit: mph
    speed_range_beaufort: false
    output_speed_unit: mph
    dynamic_speed_ranges:
      - average_below: 20
        step: 2
        max: 25
      - average_below: 50
        step: 5
        max: 50
```

Have tried in both Safari 18.2 and Chrome.
