### ISSUE TITLE
[Feature request] Show first speed range instead of full circle

### ISSUE THREAD

**Issue by olivierouellet** [aukedejong/lovelace-windrose-card#11]
It would be nice to be able to see the individual directions of the first speed range instead of a full circle. Could it be added as an option?

This is an example taken on [Plotly website ](https://plotly.com/python/wind-rose-charts/)
<img width="718" alt="Plotly example" src="https://user-images.githubusercontent.com/85790609/230788739-ef2c9194-ca9a-43d6-9169-55b025969c7c.png">

Also, it might be nice to have a option to hide the value in the middle of the graph for the first speed range (and just have the percentage in the windspeed bar).

Your card is mind blowing by the way. Thank you so much!!!

**Comment by aukedejong** [comment]
About the first speed range, not in a circle:  I'll think about this and have a look at the code. I'm afraid this will be a bigger change.
I think the reason for other windrose plots to not show the direction for the calm speeds is that the wind is not strong enough to measure a correct heading.

About hiding the center percentage: that should be easy to fix.

Hopefully I can find some time to fix the second request in the next few days.

**Comment by olivierouellet** [comment]
Thanks for your quick response.

Could we then have an option to define the first range for the calm speeds (unreliable directions) but keep the same steps? 

Let's say my `speed_range_step` is `2` m/s, we could have a `speed_range_first_step` option and set it to `0.3`. The first range would then be 0 to 0.3 (circle), the second range 0.3 to 2 (with directions), then 2 to 4 , 4 to 6 and so on. We could keep the same colour on the graph for the first and second range (from 0 to 2) so they would blend together. The windspeed bar could be kept the same and report the percentage from 0 to 2.

The idea would be to keep the circle small (proportional to the percentage of the first range?), not have strange values on the windspeed bar by shifting the rest of the values to the right (0.3 to 2.3 for example) and not have to define every step to be 0.3 .

**Comment by aukedejong** [comment]
I spend some time to see what it would take to make your first request work.

It needs to much changes at different parts in the code.  And to make it configurable would add to much complexity.
It would be a nice feature, I totally agree, but with the current code architecture, it would make it less maintainable.

I will add the config option to hide the center percentage value.  The circle will still be there.

I'm a little busy right now, but hopefully I can find some time this weekend.

**Comment by olivierouellet** [comment]
Nothing new to add, but yesterday was windy, so I thought I would share my graph with you. 
You really did an amazing work! Thanks again!
<img width="327" alt="Windy" src="https://github.com/aukedejong/lovelace-windrose-card/assets/85790609/dc153b4f-f055-42bd-9779-3381bb626ee9">

**Comment by aukedejong** [comment]
Nice.
There is a new release coming up, with a few bigger changes.
One change is your request of not having the center calm percentage. 
An other one is support for HA 5 minute statistics data.

I'm currently testing and debugging.
Hopefully I can release something this week.

**Comment by aukedejong** [comment]
Your requested feature is released.
If you see any problems, please let me know.

**Comment by olivierouellet** [comment]
I put `center_calm_percentage: false` but I don't see any change in the rendering. The percentage is still rendered.
I did install the new version and I also did a full system restart.
Thanks a lot for your hard work by the way!!!

**Comment by aukedejong** [comment]
Strange. Can you share your configuration?

**Comment by olivierouellet** [comment]
Tested in Chrome (MacOS) and Safari (iOs and MacOS)
```
type: custom:windrose-card
title: Vent 6h
hours_to_show: 6
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity: sensor.wind_direction
windspeed_entities:
  - entity: sensor.wind_speed_hi_last_2_min_davis
    name: Vent 6h
wind_direction_unit: letters
input_speed_unit: kph
output_speed_unit: kph
speed_range_step: 5
speed_range_max: 40
center_calm_percentage: false
direction_compensation: 0
windrose_draw_north_offset: -15
cardinal_direction_letters: NESO
wind_direction_count: 16
matching_strategy: direction-first
direction_speed_time_diff: 1
```
<img width="442" alt="Wind" src="https://github.com/aukedejong/lovelace-windrose-card/assets/85790609/7d3760fe-fbc7-47d6-acad-f1f5ccb2aaef">

**Comment by aukedejong** [comment]
The configuration changed in a breaking way.
I think it's easiest to just delete and add the card and modify the generated configuration.

Did you read the release notes? I'm not sure it's described clear enough in there.

**Comment by olivierouellet** [comment]
Yes, that's what I did at first (started fresh with a new card). 
Here's the default config I get : 
```
type: custom:windrose-card
title: Wind direction
hours_to_show: 4
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity: ''
windspeed_entities:
  - entity: ''
    name: ''
wind_direction_unit: degrees
input_speed_unit: mps
output_speed_unit: bft
direction_compensation: 0
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
```
If I change these configs to get a graph and add `center_calm_percentage: false` , it does nothing to the center calm percentage. I did download the latest version and restarted Home Assistant.

**Comment by aukedejong** [comment]
I think you need a browser cache refresh.
It looks like it's still loading the old version.

**Comment by olivierouellet** [comment]
Oops... Sorry, my fault! Sometimes you need to get back to the basics!
It works awesome!!! Wow. This is really a great card. Thank you again!

This config works great :
```
type: custom:windrose-card
title: Vent 6h
hours_to_show: 6
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.wind_direction
  direction_unit: letters
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.wind_speed_last_davis
    name: Vent
    speed_unit: auto
    use_statistics: false
output_speed_unit: kph
speed_range_beaufort: false
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: false
speed_range_step: 5
speed_range_max: 40
center_calm_percentage: false

```
