### ISSUE TITLE
Issue with latest build

### ISSUE THREAD

**Issue by MrMan1968** [aukedejong/lovelace-windrose-card#113]
Morning, this is how the latest build displays in my Home Assistant…
![IMG_2253](https://github.com/user-attachments/assets/a5ea81a1-b053-4af2-94e9-dfaa01a88e33)

**Comment by aukedejong** [comment]
Do you know which version still worked?
Can you share your configuration, so I can copy paste and check what's wrong?

**Comment by MrMan1968** [comment]
Morning, this is the configuration for the first gauge: -

type: custom:windrose-card
title: Wind Speed Today
data_period:
  from_hour_of_day: 0
max_width: 200
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.meteobridge_wind_direction
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.meteobridge_wind_speed
    name: Avg Speed
    speed_unit: auto
    use_statistics: false
output_speed_unit: mph
output_speed_unit_label: mph
speed_range_beaufort: false
speed_range_step: 5
speed_range_max: 30
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true

I’m not 100% certain which last build displayed correctly as I haven’t looked for a few days, and there have been a number of revisions over that time.

Regards,

Simon

**Comment by aukedejong** [comment]
Hi Simon,
Quick answer.
Ik moved some configuration option to the windspeed_entities block.
If you add some spaces in front of the out_speed_xx and speed_range_xxx properties, it should work. That way it is moved to the windspeed_entities part.  See readme for details.

This configuration is moved so you can use different speedranges and output units for different speedbars.

It was not my intention to break current config, so I made a mistake somewhere. I'll will fix.

But your current config is deprecated, so maybe it's a good idee to move the properties as described above.

Fixed config:

```yaml
type: custom:windrose-card
title: Wind Speed Today
data_period:
  from_hour_of_day: 0
max_width: 200
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.meteobridge_wind_direction
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.meteobridge_wind_speed
    name: Avg Speed
    speed_unit: auto
    use_statistics: false
    output_speed_unit: mph
    output_speed_unit_label: mph
    speed_range_beaufort: false
    speed_range_step: 5
    speed_range_max: 30
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true
```
