### ISSUE TITLE
0 bft upper border error

### ISSUE THREAD

**Issue by anotherUserWithoutUsername** [aukedejong/lovelace-windrose-card#118]
I found a misinterpretation in the calculation of the border between 0 and 1 beaufort as the 0 bft officially goes until 0,2m/s, which is 0,72km/h (below rounded 1km/h).

Symptom:
When adding a windspeedscale acording to the beaufort scale but with km/h, the steps(colors) are only the same if I set the border at 2km/h.

Root cause:
This maybe comes from the english Wikipage https://en.wikipedia.org/wiki/Beaufort_scale
where the border of 0 bft is defined as <2km/h (but see m/s which is the same as in the German Wiki and on other related Beaufort-explaining pages). The German Wiki tells us the correct border at 1km/h: https://de.wikipedia.org/wiki/Beaufortskala

My current workaround to display two matching windspeed scales with different units is to set the border at wrong 2km/h.

Suggestion:
interpret 0 bft correctly as 0-1km/h and display values of 1-5 km/h as 1 bft.

My yaml:

```
type: custom:windrose-card
title: Windrose 24h
data_period:
  hours_to_show: 24
refresh_interval: 60
windspeed_bar_location: bottom
wind_direction_entity:
  entity: sensor.gw1100a_wind_direction
  name: Windrichtung
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.gw1100a_wind_speed
    name: Windgeschwindigkeit
    speed_unit: auto
    use_statistics: false
    windspeed_bar_full: true
    output_speed_unit: kph
    speed_range_beaufort: true
    render_relative_scale: false
  - entity: sensor.gw1100a_wind_speed
    name: Windgeschwindigkeit
    speed_range_beaufort: false
    output_speed_unit: kph
    render_relative_scale: false
    speed_ranges:
      - from_value: 0
        color: rgb(0,0,255)
      - from_value: 2
        color: rgb(51,119,252)
      - from_value: 6
        color: rgb(50,187,255)
      - from_value: 12
        color: rgb(51,255,254)
      - from_value: 20
        color: rgb(51,255,186)
      - from_value: 29
        color: rgb(52,255,51)
      - from_value: 39
        color: rgb(52,255,51)
      - from_value: 49
        color: rgb(119,255,51)
      - from_value: 62
        color: rgb(187,254,50)
      - from_value: 75
        color: rgb(255,255,51)
      - from_value: 89
        color: rgb(255,187,52)
      - from_value: 103
        color: rgb(255,119,51)
      - from_value: 118
        color: rgb(255,51,52)
windrose_draw_north_offset: 0
current_direction:
  show_arrow: true
  arrow_size: 100
  center_circle_size: 30
compass_direction:
  auto_rotate: false
  entity: ""
cardinal_direction_letters: N,O,S,W
matching_strategy: direction-first
center_calm_percentage: true
corner_info:
  top_left:
    label: aktueller Wind
    unit: " km/h"
    entity: sensor.gw1100a_wind_speed
  top_right:
    label: max Böen Tag
    unit: " km/h"
    entity: sensor.gw1100a_max_daily_gust

```
