### ISSUE TITLE
Setting custom labels but not updating on the card

### ISSUE THREAD

**Issue by beta-j** [aukedejong/lovelace-windrose-card#123]
I am trying to show intercardinal directions in my local language (Maltese).  I have declared the cardinal directions using ``cardinal_direction_letters: TLNP`` and then used ``customLabels`` to declare the rest.  However the card only shows the updated cardinal directions and is using combinations of these to generate the intercardinal directions.  So, for example in the Maltese language (N)orth is (T)ramuntana, (N)orth (East) is (G)rigal and (E)ast is (L)vant, so I would like my card to show `T`,`G` and `L`, but instead it is showing `T`, `TL` and `L`  (see screenshot).

Is something wrong with my card config?

![Image](https://github.com/user-attachments/assets/8a8f6e57-5d15-4386-9b7e-540acf94212c)

```yaml
type: custom:windrose-card
title: Wind direction
data_period:
  from_hour_of_day: 0
max_width: 400
refresh_interval: 300
windspeed_bar_location: right
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.iejtun3_wind_direction_degrees
  direction_unit: degrees
  use_statistics: true
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.iejtun3_wind_speed
    name: Wind Speed
    speed_unit: auto
    use_statistics: true
    windspeed_bar_full: false
    speed_range_beaufort: true
  - entity: sensor.iejtun3_wind_gust
    name: Gusts
    speed_unit: auto
    use_statistics: true
    windspeed_bar_full: false
    speed_range_beaufort: true
    speed_ranges:
      - from_value: 0
        color: rgb(0,255,0)
      - from_value: 2
        color: yellow
      - from_value: 5
        color: hsl(200, 100%, 60%)
      - from_value: 10
        color: orange
      - from_value: 15
        color: red
output_speed_unit: kph
speed_range_beaufort: true
windrose_draw_north_offset: 0
direction_labels:
  cardinal_direction_letters: TLNP
  show_intercardinal_directions: true
  show_secondary_intercardinal_directions: false
  cardinal_directions_text_size: 60
  intercardinal_directions_text_size: 45
  secondary_intercardinal_directions_text_size: 30
  customLabels:
    "n": T
    e: L
    s: "N"
    w: P
    ne: G
    se: X
    sw: Lb
    nw: M
matching_strategy: speed-first
center_calm_percentage: true
wind_direction_count: 8
background_image: https://<REDACTED>/local/home_plans/home_plan_4.png
current_direction:
  show_arrow: true
  arrow_size: 80
  centre_circle_size: 30
corner_info:
  top_left:
    label: "Current Gust Speed:"
    entity: sensor.iejtun3_wind_gust
    unit: km/h
    label_text_size: 50
    value_text_size: 50
    inputUnit: kph
    outputUnit: kph
  top_right:
    label: "Wind Direction:"
    entity: sensor.iejtun3_wind_direction_cardinal
    color: red
  bottom_right:
    label: Wind Chill
    entity: sensor.iejtun3_wind_chill
    unit: °C
    label_text_size: 30
    value_text_size: 40
  bottom_left:
    label: Heat Index
    entity: sensor.iejtun3_heat_index
    unit: °C
    label_text_size: 30
    value_text_size: 40
actions:
  top_left:
    tap_action:
      entity: sensor.iejtun3_wind_gust
      action: more-info
  top_right:
    tap_action:
      entity: sensor.iejtun3_wind_direction_cardinal
      action: more-info
  windrose:
    tap_action:
      entity: sensor.iejtun3_wind_direction_degrees
      action: more-info
  bottom_right:
    tap_action:
      entity: sensor.iejtun3_wind_chill
      action: more-info
  bottom_left:
    tap_action:
      entity: sensor.iejtun3_heat_index
      action: more-info
  speed_bar_1:
    tap_action:
      entity: sensor.iejtun3_wind_speed
      action: more-info
  speed_bar_2:
    tap_action:
      entity: sensor.iejtun3_wind_gust
      action: more-info
colors:
  rose_lines: gray
  rose_direction_letters: gray
  rose_center_percentage: white
  rose_percentages: black
  rose_current_direction_arrow: red
  bar_border: black
  bar_unit_name: gray
  bar_name: black
  bar_unit_values: auto
  bar_percentages: auto
```
