### ISSUE TITLE
Option to add additional info above/below windrose

### ISSUE THREAD

**Issue by MiOrt** [aukedejong/lovelace-windrose-card#125]
I would like to have the option to display additional entity-info (like corner info) above/below the windrose. That would give some space within the card for additional wind infos like the natural description of current bft and additional converted units. Maybe this could be implemented as new object "Object top_bottom_info" with objects "top_info" and "bottom_info" (same structure as corner_info objects). Maybe for the bottom_info it would be nice to have the choice above/below horizontal bars.

Use case: Currently all data on my card is displayed in mps. I added a helper that translates the windspeed into the beaufort descriptions and converts current mps in kmp. I display this entity in an extra entity card below the windrose-card like "37 km/h - frische Briese". Would be great to have all that information in one place.

**Comment by aukedejong** [comment]
Yes, good idea.
I'm also thinking about the possibility to display information about the data used in the card with placeholders.
Data like, measurements counts, minimums, maximums.

For example:   'Matched measurements: ${matchMeasurements},  average windspeed: ${average} mps'

**Comment by aukedejong** [comment]
Released version 1.21.0
Added option to modify the current speed arrow location.
Options are below, above, left and right.

Example:

 ```yaml
windspeed_entities:
  - entity: sensor.wind_speed
    name: Speed
    speed_unit: auto
    output_speed_unit: kph
    windspeed_bar_full: false
    speed_range_beaufort: false
    current_speed_arrow: true
    current_speed_arrow_size: 50
    current_speed_arrow_location: below
    use_statistics: false
    bar_label_text_size: 40
    bar_speed_text_size: 40
    bar_percentage_text_size: 40
  ```

The text size options are also new.
