### ISSUE TITLE
Attribute support for windspeed

### ISSUE THREAD

**Issue by fishter** [aukedejong/lovelace-windrose-card#129]
I noticed the latest release (1.14.1) includes support for attributes. I wanted to try this as I've been using a template sensor to pull out the attributes of wind speed and direction just for the windrose card.

But, I found that if I add an attribute entry for windspeed_entities to my config I get no rose regenerated at all.

The wind_direction entry handles the attribute ok and still produces an output, but the windspeed_entities doesn't like it.

Here's the working config:
```
type: custom:windrose-card
title: Wind direction (last 24hr)
data_period:
  hours_to_show: 24
wind_direction_entity:
  entity: weather.forecast_home
  attribute: wind_bearing
windspeed_entities:
  - entity: sensor.home_wind_speed
current_direction:
  show_arrow: true
```
And here's the non working:
```
type: custom:windrose-card
title: Wind direction (last 24hr)
data_period:
  hours_to_show: 24
wind_direction_entity:
  entity: weather.forecast_home
  attribute: wind_bearing
windspeed_entities:
  - entity: weather.forecast_home
    attribute: wind_speed
current_direction:
  show_arrow: true
```
I've checked my attribute names in the template editor and they produce the right values.

Am I using the right syntax for the attribute in the config?
