### ISSUE TITLE
V1.15.1 is no longer centred in the element.

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#131]
Since V1.15.1 the windrose is no longer displayed within the element, see screenshot.

<img width="383" alt="Image" src="https://github.com/user-attachments/assets/a9d00901-8f1a-4d3b-a3c5-b7916b543825" />

HA is 2025.1.4. Confirmed issue is both in the App, Chrome and Safari.

Configuration

```
type: custom:windrose-card
data_period:
  hours_to_show: 6
refresh_interval: 300
output_speed_unit_label: mph
windspeed_bar_location: right
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.wind_dir
windspeed_entities:
  - entity: sensor.wind_speed
    name: speed
    speed_unit: mph
    speed_range_beaufort: false
    output_speed_unit: mph
    dynamic_speed_ranges:
      - average_above: 0
        step: 2.5
        max: 25
      - average_above: 15
        step: 5
        max: 50
  - entity: sensor.wind_gust_speed
    name: gust
    speed_unit: mph
    speed_range_beaufort: false
    output_speed_unit: mph
    dynamic_speed_ranges:
      - average_above: 0
        step: 2.5
        max: 25
      - average_above: 15
        step: 5
        max: 45
      - average_above: 50
        step: 7.5
        max: 65
matching_strategy: full-time
center_calm_percentage: false
current_direction:
  show_arrow: true
  arrow_size: 60
corner_info:
  top_left:
    label: Current windspeed
    unit: mph
    entity: sensor.wind_speed
  bottom_left:
    label: Gust windspeed
    unit: mph
    entity: sensor.wind_gust_speed
  top_right:
    label: Temp
    entity: sensor.outside_temperature
    unit: C°
  bottom_right:
    label: Chill
    entity: sensor.wind_chill
    unit: C°
actions:
  top_left:
    tap_action:
      entity: sensor.wind_speed
      action: more-info
  windrose:
    tap_action:
      entity: sensor.wind_dir
      action: more-info
  bottom_left:
    tap_action:
      entity: sensor.wind_gust_speed
      action: more-info
  speed_bar_1:
    tap_action:
      entity: sensor.wind_speed
      action: more-info
  speed_bar_2:
    tap_action:
      entity: sensor.wind_gust_speed
      action: more-info
  top_right:
    tap_action:
      entity: sensor.outside_temperature
      action: more-info
  bottom_right:
    tap_action:
      entity: sensor.wind_chill
      action: more-info
```
