### ISSUE TITLE
Getting "e is undefined" since v1.16

### ISSUE THREAD

**Issue by OverZealous** [aukedejong/lovelace-windrose-card#133]
I tried both `1.16` and `1.16.1`, and I'm now getting an `e is undefined` error.

I rolled back to `1.15.2` and it loaded as before.

Here is my configuration:

```yaml
type: custom:windrose-card
title: Wind Direction (Last 8 Hours)
hours_to_show: 8
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.stormbreaker_wind_dir
windspeed_entities:
  - entity: sensor.stormbreaker_wind_speed
    name: Wind Speed
wind_direction_unit: degrees
input_speed_unit: mph
output_speed_unit: mph
direction_compensation: 0
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
```

I tried simplifying my configuration down to just the `wind_direction_entity`, but it still won't load.

![Image](https://github.com/user-attachments/assets/4a34309e-d49b-4054-9260-9b8200558784)

The error details (such as they are) are:

```
card custom:windrose-card TypeError: e is undefined
    fromConfig windrose-card.js:50
    Gt windrose-card.js:50
    setConfig windrose-card.js:65
    a create-element-base.ts:153
    u create-element-base.ts:179
    u create-element-base.ts:285
    c create-element-base.ts:242
    v create-card-element.ts:107
    value hui-card.ts:123
    value hui-card.ts:152
    n fire_event.ts:75
    u create-element-base.ts:198
create-element-base.ts:252:12
```
