### ISSUE TITLE
Feature request: Background color option for inactive period buttons.

### ISSUE THREAD

**Issue by Al-Dek** [aukedejong/lovelace-windrose-card#134]
I think it will be useful to be able to adjust the background color for inactive period buttons. This will clearly display the buttons, as in my case when they are masked by the card background image.

![Image](https://github.com/user-attachments/assets/b5fe96ba-fdf1-4a8c-9368-3625debef80a)

**Comment by aukedejong** [comment]
Fixed in version 1.18.0

```
data_period:
  period_selector:
    location: bottom
    active_color: black
    active_bg_color: yellow
    color: red
    bg_color: black
    buttons:
      - hours: 1
        title: 1 hour
      - hours: 8
        title: 8 hours
      - hours: 24
        title: 1 day
        active: true
      - hours: 240
        title: 10 days
```

Thanks!
