### ISSUE TITLE
Help with Wind Direction

### ISSUE THREAD

**Issue by deanfourie1** [aukedejong/lovelace-windrose-card#137]
I want to start by saying thanks so much for all the effect being put into this card! This card has always brought so much color and life to my dashboard and seeing all these cool new features is so awesome! Thanks so much for your time and effort, it looks AWESOME!

I am trying to get Wind Direction to display at the top right, to show the direction in either,

N
E
S
W
NE
ENE
NNE
SE
SSE
ESE
SW
SSW
SWW

Instead, it is showing like this.

![Image](https://github.com/user-attachments/assets/e1008bec-0a4e-4399-90ec-c40f7e563a16)

Not sure how to use the  `direction_letters: NESW` part of the code.

Thanks!

```
type: custom:windrose-card
data_period:
  hours_to_show: 12
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.weather_station_wind_direction
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.weather_station_friendly_name_wind_speed_km_h
    name: ""
    speed_unit: auto
    use_statistics: false
show_current_direction_arrow: true
output_speed_unit: mps
speed_range_beaufort: true
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true
entity: sensor.weather_station_wind_direction
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
compass_direction:
  auto_rotate: true
  entity: sensor.weather_station_wind_direction
corner_info:
  top_left:
    label: Wind Speed
    unit: " km/h"
    entity: sensor.weather_station_friendly_name_wind_speed_km_h
    label_text_size: 50
    value_text_size: 60
    input_unit: kph
    output_unit: kph
    precision: 2
  top_right:
    label: Wind direction
    unit: °
    color: red
    label_text_size: 50
    value_text_size: 60
    entity: sensor.weather_station_wind_direction
    input_unit: degrees
    output_unit: letters
    direction_letters: NESW
  bottom_left:
    label: Compass
    label_text_size: 50
    value_text_size: 60
    unit: °
    entity: sensor.weather_station_wind_direction
actions:
  top_left:
    tap_action:
      entity: sensor.weather_station_friendly_name_wind_speed_km_h
      attribute: wind_speed
      action: more-info
  top_right:
    tap_action:
      entity: sensor.weather_station_wind_direction
      attribute: wind_speed
      action: more-info
  windrose:
    tap_action:
      entity: sensor.wind_direction
      action: more-info
  bottom_left:
    tap_action:
      entity: sensor.weather_station_wind_direction
      action: more-info
  speed_bar_1:
    tap_action:
      entity: sensor.wind_speed
      action: more-info
  speed_bar_2:
    tap_action:
      entity: sensor.wind_gust
      action: more-info
direction_labels:
  cardinal_direction_letters: ABCD
  show_cardinal_directions: true
  show_intercardinal_directions: true
  show_secondary_intercardinal_directions: true
  cardinal_directions_text_size: 60
  intercardinal_directions_text_size: 45
  secondary_intercardinal_directions_text_size: 30
  custom_labels:
    "n": "N"
    e: E
    s: S
    w: W
    ne: NE
    se: SE
    sw: SW
    nw: NW
    nne: NNE
    ene: ENE
    ese: ESE
    sse: SSE
    ssw: SSW
    wsw: WSW
    wnw: WNW
    nnw: NNW
```

**Comment by aukedejong** [comment]
I'm not sure, but maybe adding an x to the direction_letters option.
This is also the default value, so maybe removing the property also works.

```
  top_right:
    label: Wind direction
    unit: °
    color: red
    label_text_size: 50
    value_text_size: 60
    entity: sensor.weather_station_wind_direction
    input_unit: degrees
    output_unit: letters
    direction_letters: NESWX
```

Not causing this issue, but  also  the custom_labels config you use looks like the default.

**Comment by deanfourie1** [comment]
> I'm not sure, but maybe adding an x to the direction_letters option. This is also the default value, so maybe removing the property also works.
> 
> ```
>   top_right:
>     label: Wind direction
>     unit: °
>     color: red
>     label_text_size: 50
>     value_text_size: 60
>     entity: sensor.weather_station_wind_direction
>     input_unit: degrees
>     output_unit: letters
>     direction_letters: NESWX
> ```
> 
> Not causing this issue, but also the custom_labels config you use looks like the default.

Sorry I am a little confused as how to set these up? As previously, I did not need to configure anything, it seemed that the wind direction was just right, obviously things are a little more involved now.

Do I need to find out at what point on the card the wind is at NE, then add that somewhere in the right place,

If that makes sense haha.

Thanks

**Comment by aukedejong** [comment]
I think you copy pasted the max configuration from the readme into Home Assistant, is that right?

Maybe it better to just start with the minimal or the generated config and add config you need.

For example, the compass config is used with a compass entity, usually on an boat.  This will rotate the wind rose, depending on the compass.  You used the wind direction entity as compass entity. 

I hope below config works. It works with my HA with my entities.

```
type: custom:windrose-card
data_period:
  hours_to_show: 12
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.weather_station_wind_direction
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.weather_station_friendly_name_wind_speed_km_h
    name: ""
    speed_unit: auto
    use_statistics: false
show_current_direction_arrow: true
output_speed_unit: mps
speed_range_beaufort: true
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
corner_info:
  top_left:
    label: Wind Speed
    unit: " km/h"
    entity: sensor.weather_station_friendly_name_wind_speed_km_h
    label_text_size: 50
    value_text_size: 60
    input_unit: kph
    output_unit: kph
    precision: 2
  top_right:
    label: Wind direction
    unit: °
    color: red
    label_text_size: 50
    value_text_size: 60
    entity: sensor.weather_station_wind_direction
    input_unit: degrees
    output_unit: letters
    direction_letters: NESWX
direction_labels:
  cardinal_direction_letters: ABCD
  show_cardinal_directions: true
  show_intercardinal_directions: true
  show_secondary_intercardinal_directions: true
  cardinal_directions_text_size: 60
  intercardinal_directions_text_size: 45
  secondary_intercardinal_directions_text_size: 30
```
