### ISSUE TITLE
Feature Request: Configurable Scaling Factor(s)

### ISSUE THREAD

**Issue by brianmcentire** [aukedejong/lovelace-windrose-card#138]
Love the windrose!

I have found, due to siting (and possible design flaws too), my WeatherFlow Tempest weather station reads about 3.5x lower mph wind speeds and gusts than those reported by the local airport weather observations about 1.5 miles away from me. I actually determined gusts are 3.75x low and wind speeds are 3.25x low.

In my grafana dashboards, when I scale the values reported by my station by those amounts, they are tightly correlated to the METAR observations.

Could a YAML configuration scaling factor be included so that people can account for siting and device issues to correct them to match real world conditions / authoritative weather observations?

**Comment by aukedejong** [comment]
I think we should add a factor and absolute compensation options.

A factor differents could also be caused be the wrong unit of measurement.  km/h and m/s is a factor 3.6 difference.

**Comment by aukedejong** [comment]
Added this feature in version 1.23.0

Example config:
```yaml
windspeed_entities:
  - entity: sensor.wind_speed
    name: Speed
    speed_unit: auto
    output_speed_unit: kph
    windspeed_bar_full: false
    speed_range_beaufort: false
    use_statistics: false
    speed_range_step: 15
    speed_range_max: 149
    speed_compensation_factor: 1
    speed_compensation_absolute: 0
```

Happy to hear your thoughts.
