### ISSUE TITLE
Feature Request - option to move arrows to the other side of the bar graphs

### ISSUE THREAD

**Issue by KruseLuds** [aukedejong/lovelace-windrose-card#139]
Note this:

![Image](https://github.com/user-attachments/assets/ba929aa8-a155-4867-80e0-b91f0519b644)

Alot of the time the arrows in the wind bar graphs are covering up the label for the graph, so it would be great to have an option to show the arrow on the other saide of those bar graphs - ?

**Comment by aukedejong** [comment]
Released version 1.21.0
Added option to modify the current speed arrow location.
Options are below, above, left and right.

Example:

 ```yaml
windspeed_entities:
  - entity: sensor.wind_speed
    name: Speed
    speed_unit: auto
    output_speed_unit: kph
    windspeed_bar_full: false
    speed_range_beaufort: false
    current_speed_arrow: true
    current_speed_arrow_size: 50
    current_speed_arrow_location: below
    use_statistics: false
    bar_label_text_size: 40
    bar_speed_text_size: 40
    bar_percentage_text_size: 40
  ```

The text size options are also new.
