### ISSUE TITLE
Bar labels "overflow: visible"

### ISSUE THREAD

**Issue by mloraas** [aukedejong/lovelace-windrose-card#143]
Hello Auke,
Thank you for a great card!

When defining custom speed_ranges with two digits and one decimal, the last digit gets "cut".

![Image](https://github.com/user-attachments/assets/6e9b375b-065c-4a0e-badd-bba8e6eaf7f9)

The csv-container may need "overflow: visible;" to be set, or the margins may need to be adjusted.

Have a good day!

Best regards,
-mLoraas

**Comment by aukedejong** [comment]
Hello mLoraas,

I think the margin should be increased, currently the margin does not grow when the numbers get longer.

Did a test, but I can't reproduce it with your numbers.   I'm not sure why.

Can you share your card configuration?
Are you using the latest version of the card?

**Comment by mloraas** [comment]
![Image](https://github.com/user-attachments/assets/b6282094-f71f-4e9b-8c90-673619a87e58)

```
type: grid
cards:
  - type: custom:windrose-card
    background_image: /local/windrose_background_color.png
    data_period:
      period_selector:
        location: bottom
        active_color: white
        active_bg_color: blue
        buttons:
          - hours: 1
            title: 1 time
            active: true
          - hours: 8
            title: 8 timer
          - hours: 24
            title: 1 dag
    refresh_interval: 300
    windspeed_bar_location: right
    wind_direction_entity:
      entity: sensor.vindretning_grader
      use_statistics: false
      direction_compensation: 0
    windspeed_entities:
      - entity: sensor.vindstyrke
        name: Vindstyrke
        render_relative_scale: false
        speed_range_beaufort: false
        speed_ranges:
          - from_value: 0
            color: lightgrey
          - from_value: 0.3
            color: "#AEF1F9"
          - from_value: 1.6
            color: "#96F7DC"
          - from_value: 3.4
            color: "#96F7B4"
          - from_value: 5.5
            color: "#6FF46F"
          - from_value: 8
            color: "#73ED12"
          - from_value: 10.8
            color: "#A4ED12"
          - from_value: 13.9
            color: "#DAED12"
          - from_value: 17.2
            color: "#EDC212"
          - from_value: 20.8
            color: "#ED8F12"
          - from_value: 24.5
            color: "#ED6312"
          - from_value: 28.5
            color: "#ED2912"
          - from_value: 32.7
            color: "#D5102D"
    current_direction:
      show_arrow: true
      arrow_size: 80
    cardinal_direction_letters: N,Ø,S,V
    matching_strategy: full-time
    center_calm_percentage: true
    hide_windspeed_bar: false
    card_width: 4
    colors:
      rose_lines: black
      rose_cardinal_direction_labels: black
      rose_center_percentage: black
      rose_percentages: blue
      rose_current_direction_arrow: red
      bar_name: white
    corner_info:
      top_left:
        label: Vindmåler
        unit: " m/s"
        entity: sensor.vindstyrke
        value_text_size: 60
        label_text_size: 73

```
