### ISSUE TITLE
Rotate with hiding gone wrong.

### ISSUE THREAD

**Issue by alnavasa** [aukedejong/lovelace-windrose-card#145]
Hi, I am trying to rotate with heading and I don't get it to work, I compare with another wind rose instrument I have and is completely off, I tried to tilt it -90 degrees but issue is still there. 

code 

```
type: custom:windrose-card
title: false
data_period:
  hours_to_show: 24
refresh_interval: 300
windspeed_bar_location: bottom
wind_direction_entity:
  entity: sensor.ii_mwd_1
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.ii_mwd_5
    name: TWS
    speed_unit: knots
    use_statistics: false
    windspeed_bar_full: false
    output_speed_unit: knots
    speed_range_beaufort: false
direction_labels:
  cardinal_direction_letters: NESW
windrose_draw_north_offset: -90
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
compass_direction:
  auto_rotate: true
  entity: sensor.ii_hdt_1
cardinal_direction_letters: N,E,S,W
matching_strategy: direction-first
center_calm_percentage: true

```

<img width="723" alt="Image" src="https://github.com/user-attachments/assets/ce48a8a7-87c0-4c70-989b-5f70495db248" />
<img width="182" alt="Image" src="https://github.com/user-attachments/assets/3029607b-3f90-4543-b8f8-6bd01c9435c8" />
