### ISSUE TITLE
hide_direction_below_speed: Not Working

### ISSUE THREAD

**Issue by JulianDHall** [aukedejong/lovelace-windrose-card#161]
![Image](https://github.com/user-attachments/assets/ed3dd66d-e34d-410e-b439-90a625012b21)

Been seeing some strange behaviour; my card is on the right and I have set up a new card on the left with your minimal set-up. Problem: Current gust is >10knots but when using:

``  hide_direction_below_speed: 5``

the direction arrow disappears and the center rose is still visible (with zero percent).  I have the same settings on the left but with many more settings.  Right hand yaml is:

```yaml
type: custom:windrose-card
title: Wind direction
data_period:
  hours_to_show: 4
refresh_interval: 300
windspeed_bar_location: bottom
wind_direction_entity:
  entity: sensor.weather_wind_direction
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.weather_wind_gust_5min
    name: ""
    speed_unit: auto
    use_statistics: false
    windspeed_bar_full: false
    output_speed_unit: knots
    speed_range_beaufort: false
    render_relative_scale: true
direction_labels:
  cardinal_direction_letters: NESW
windrose_draw_north_offset: 0
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
  hide_direction_below_speed: 5
compass_direction:
  auto_rotate: false
  entity: ""
cardinal_direction_letters: N,E,S,W
matching_strategy: direction-first
center_calm_percentage: true
```
