### ISSUE TITLE
Remove "X" from wind direction

### ISSUE THREAD

**Issue by kd7eir** [aukedejong/lovelace-windrose-card#164]
I love this card, but the insane injection of "X" in wind speed directions drives me crazy. I have pared down my yaml to this:

```yaml
type: custom:windrose-card
title: Wind Rose
data_period:
  period_selector:
    location: bottom
    active_color: black
    active_bg_color: yellow
    buttons:
      - hours: 1
        title: 1 hour
      - hours: 8
        title: 8 hours
      - hours: 24
        title: 1 day
        active: true
      - hours: 240
        title: 10 days
refresh_interval: 100
windspeed_bar_location: bottom
wind_direction_entity:
  entity: sensor.gw3000b_wind_direction
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.gw3000b_wind_gust
    name: Speed
    speed_unit: auto
    use_statistics: false
    windspeed_bar_full: true
    output_speed_unit: mph
    speed_range_beaufort: true
  - entity: sensor.gw3000b_wind_gust
    name: Gust
    speed_unit: auto
    use_statistics: false
    windspeed_bar_full: true
    output_speed_unit: mph
    speed_range_beaufort: false
    speed_ranges:
      - from_value: 0
        color: rgb(0,255,0)
      - from_value: 2
        color: yellow
      - from_value: 5
        color: hsl(200, 100%, 60%)
      - from_value: 10
        color: orange
      - from_value: 15
        color: red
windrose_draw_north_offset: 0
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
  hide_direction_below_speed: 3
compass_direction:
  auto_rotate: false
  as_heading: false
  entity: input_number.compass
corner_info:
  top_left:
    label: Current gust speed
    unit: " MPH"
    entity: sensor.gw3000b_wind_gust
    label_text_size: 50
    value_text_size: 50
    input_unit: mph
    output_unit: mph
    precision: 1
  top_right:
    label: Wind direction
    unit: °
    color: red
    entity: sensor.gw3000b_wind_direction_10m_avg
    input_unit: degrees
    output_unit: letters
  bottom_left:
    label: Compass
    unit: °
    entity: sensor.gw3000b_wind_direction
    label_text_size: 40
  bottom_right:
    label: Solar Lux lx
    entity: sensor.gw3000b_solar_lux
    label_text_size: 40
actions:
  top_left:
    tap_action:
      entity: sensor.gw3000b.wind_gust
      action: more-info
  top_right:
    double_tap_action:
      entity: switch.light
      action: toggle
  windrose:
    tap_action:
      action: navigate
      navigation_path: /lovelace/plattegrond-tablet
  bottom_right:
    tap_action:
      entity: sensor.rain
      action: more-info
  bottom_left:
    tap_action:
      action: url
      url_path: https://www.home-assistant.io
  speed_bar_1:
    tap_action:
      entity: sensor.gw3000b.temp_outside
      action: more-info
  speed_bar_2:
    tap_action:
      entity: sensor.max_temp_outside
      action: more-info
show_intercardinal_directions: false
show_secondary_intercardinal_directions: false
matching_strategy: full-time
background_image: /hacsfiles/lovelace-windrose-card/bg.png
center_calm_percentage: true
colors:
  rose_lines: rgb(0,255,0)
  rose_cardinal_direction_labels: green
  rose_intercardinal_direction_labels: purple
  rose_secondary_intercardinal_direction_labels: yellow
  rose_center_percentage: red
  rose_percentages: blue
  rose_current_direction_arrow: purple
  bar_border: hsl(200, 100%, 60%)
  bar_unit_name: purple
  bar_name: yellow
  bar_unit_values: blue
  bar_percentages: auto
```

Any help is greatly appreciated.
