### ISSUE TITLE
Card Blank

### ISSUE THREAD

**Issue by sanderlv** [aukedejong/lovelace-windrose-card#19]
HI, I followed all steps in the manual including the error ones. I have a blank card with the default config...

What steps can I try?

**Comment by sanderlv** [comment]
Also, the tip from "error section" gives:

```
Logger: homeassistant.components.frontend
Source: components/frontend/__init__.py:335
Integration: Home Assistant Frontend (documentation, issues)
First occurred: 09:28:56 (1 occurrences)
Last logged: 09:28:56

Please remove javascript_version from your frontend config. It is no longer supported
```

**Comment by aukedejong** [comment]
Do you see the windrose circles or is it complete blank?

How did you install the card? Hacs or manual?

In the browser console, press F12 in the browser to show. Are there any windrose card errors?
Do you see the version banner?

**Comment by sanderlv** [comment]
Complete blank.

HACS install.

```
Uncaught (in promise) TypeError: this.directionData is undefined
    matchDirectionLeading http://domain.nl:8123/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=5912706960110:597
    match http://domain.nl:8123/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=5912706960110:562
    updateWindData http://domain.nl:8123/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=5912706960110:1465
[windrose-card.js:597:9](http://domain.nl:8123/hacsfiles/lovelace-windrose-card/windrose-card.js?hacstag=5912706960110)
```

**Comment by aukedejong** [comment]
Can you post your card configuration?

**Comment by sanderlv** [comment]
Something is coming to life...

Not there yet, but little steps...

```
type: custom:windrose-card
title: Wind direction
max_width: 400
windspeed_bar_full: true
wind_direction_entity: sensor.buienradar_wind_direction
windspeed_entities:
  - entity: sensor.buienradar_wind_speed
    name: Average
input_speed_unit: mps
output_speed_unit: mps
speed_ranges:
  - from_value: 0
    color: rgb(0,255,0)
  - from_value: 5
    color: yellow
  - from_value: 10
    color: hsl(200, 100%, 60%)
  - from_value: 20
    color: orange
  - from_value: 40
    color: red

```
![image](https://user-images.githubusercontent.com/16528916/235508768-c6ac4918-5793-49e1-81cb-e8cda3d59d61.png)
