### ISSUE TITLE
Input speed kph, output mps gives blank display

### ISSUE THREAD

**Issue by tangix** [aukedejong/lovelace-windrose-card#20]
I am sure I'm doing something wrong, please let me know. This is my config:
```
type: custom:windrose-card
hours_to_show: 4
max_width: 400
refresh_interval: 300
windspeed_bar_location: right
windspeed_bar_full: false
wind_direction_entity: sensor.ws3500_wind_direction
windspeed_entities:
  - entity: sensor.ws3500_wind_speed
    name: ''
wind_direction_unit: degrees
input_speed_unit: kph
output_speed_unit: mps
direction_compensation: 0
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
```
This gives:
<img width="420" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/1013635/efeae6fa-886d-4f1a-9110-2ccb9e2dc16a">

`kph` / `kph` gives:
<img width="397" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/1013635/8fcc4b78-aa93-45fa-931c-16ede3e77da9">

Version 0.11.0 on HA 2023.4.6
