### ISSUE TITLE
Card does not show direction

### ISSUE THREAD

**Issue by DirkMu** [aukedejong/lovelace-windrose-card#21]
I am using a sensor from my KNX wind sensor which provides wind direction in degrees. Unfortunately the card does not show the distribution of the wind direction:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/53949754/97afc442-a26c-435a-89f0-174d0d6ec55b)

```
type: custom:windrose-card
title: Wind direction
hours_to_show: 24
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity: sensor.ws_dach_wind_richtung
windspeed_entities:
  - entity: sensor.ws_dach_wind
    name: Dach
wind_direction_unit: degrees
input_speed_unit: mps
output_speed_unit: mps
direction_compensation: 0
windrose_draw_north_offset: -32
cardinal_direction_letters: NOSW
matching_strategy: speed-first
direction_speed_time_diff: 1
```
