### ISSUE TITLE
Console Error - No matching speed found for direction.

### ISSUE THREAD

**Issue by jazzyisj** [aukedejong/lovelace-windrose-card#23]
HASS - v2023.5.3
Windrose: v0.11.0

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/44064559/0d1b4a47-4ed0-4c56-bc5d-c5493d4a3726)

**Comment by aukedejong** [comment]
This means that the direction and speed measurements are not close enough in time. Default is 1second before or after.

You can try to increase direction_speed_time_diff config value.
Changing the matching-strategy can also help.

You don't see anything in the windrose graph?

**Comment by jazzyisj** [comment]
I was getting results in the windrose, but also tonnes of console errors.  I've changed my config, now I'm only getting a handful of errors.  I played with the settings a bit, this was the best I could do.

<img width="493" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/44064559/601b518d-374c-42e3-8038-4ab1197719b6">

```
type: custom:windrose-card
title: Wind Direction
max_width: 400
windspeed_bar_full: true
wind_direction_entity: sensor.wind_bearing
wind_direction_unit: degrees
windspeed_entities:
  - entity: sensor.wind_speed
    name: Average
input_speed_unit: kph
output_speed_unit: kph
direction_speed_time_diff: 10
matching_strategy: speed-first
```
