### ISSUE TITLE
Card stopped working after update

### ISSUE THREAD

**Issue by mattfox27** [aukedejong/lovelace-windrose-card#29]
![wind](https://github.com/aukedejong/lovelace-windrose-card/assets/6801877/60a01103-3fb0-4f90-8bc2-a495fcdf99b9)
After latest update I get an error that no wind direction entity is present....its using the same config as before

**Comment by bram2202** [comment]
Same here.

``` yaml
type: custom:windrose-card
title: Wind direction
wind_direction_entity:
  - entity: sensor.pws_wind_direction
windspeed_entities:
  - entity: sensor.pws_wind_speed
```

Error:
```
WindRoseCard: No wind_direction_entity.entity configured
```

**Comment by olivierouellet** [comment]
There was some breaking changes in the [last version](https://github.com/aukedejong/lovelace-windrose-card/releases/tag/v1.0.0) for the configs.
Seems like your configs need some adjustment. Use this form :
```
wind_direction_entity:
  entity: sensor.wind_direction
windspeed_entities:
  - entity: sensor.wind_speed
```
So mattfox27 needs to add two spaces and bram2202 needs to remove the dash and use only 2 spaces.
I think the difference in the yaml comes from the fact you can have two `windspeed_entities` but only one `wind_direction_entity` .

You'll also need to change the input_speed_unit, the wind_direction_unit and the direction_compensation.
And you should remove `direction_speed_time_diff` which is not used anymore.

Here's one config that works :
```
type: custom:windrose-card
title: Wind Rose
hours_to_show: 6
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.wind_direction
  direction_unit: letters
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.wind_speed
    name: Wind 6h
    speed_unit: auto
    use_statistics: false
output_speed_unit: kph
speed_range_beaufort: false
windrose_draw_north_offset: -15
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: false
speed_range_step: 5
speed_range_max: 40
```
