### ISSUE TITLE
empty panel after HA update to 2023.6.1

### ISSUE THREAD

**Issue by TobiasSchwarz74** [aukedejong/lovelace-windrose-card#30]
After updating HA to version 2023.6.1 there is only an empty panel.
Using latest windrose card version 1.0.0.

```
  - type: custom:windrose-card
    windspeed_bar_full: true
    speed_range_beaufort: false
    input_speed_unit: kph
    output_speed_unit: kph
    cardinal_direction_letters: NOSW
    windspeed_entities:
      - entity: sensor.gw1100a_v2_2_3_wind_speed
        name: ''
    wind_direction_entity:
      entity: sensor.gw1100a_v2_2_3_wind_direction
```

**Comment by olivierouellet** [comment]
Remove the `input_speed_unit` and put `speed_unit` under `windspeed_entities`
```
wind_direction_entity:
  entity: sensor.gw1100a_v2_2_3_wind_direction
windspeed_entities:
  - entity: sensor.gw1100a_v2_2_3_wind_speed
    speed_unit: kph
```
If it remains blank, please use Chrome and go to View > Developer > Developer tools. Do you see any error?

**Comment by olivierouellet** [comment]
Maybe same issue as #26 then.

 If you do a full restart of Home Assistant, does the card go blank again? Any errors in the Developper tools?

**Comment by ildar170975** [comment]
In my case the card is not displayed at all:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/72add0cd-ce0a-4843-8488-a604632e45c1)

It is displayed in Editor as blank:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/3c6cb8c7-1fdb-4533-8d45-787946d6333d)

See no errors in Code Inspector.
But when I open Editor - only then I see an error:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/63a9cc89-61b5-4d68-859c-7d90e65efdb1)

**Comment by ildar170975** [comment]
The code:
```
type: custom:windrose-card
title: Wind direction
wind_direction_entity:
  entity: sensor.xxx_gismeteo_wind_bearing
windspeed_entities:
  - entity: sensor.xxx_gismeteo_wind_speed
    name: Home
hours_to_show: 8
```
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/e5a7d5f1-7fe2-477a-9a83-7eb8a7e40883)

Chrome + Win10.

The card is still not displayed (F5 does not help):
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/4b1246c5-dede-414a-a472-54fba3dfe0f2)

There are no errors in Code Inspector.

In Editor:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/6bed1e72-3051-4dbe-8e90-583f0a6a4386)

Still no errors in Code Inspector.

------------------

With `hours_to_show: 9`:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/e3661fe8-aeff-4e2e-b85d-478e4a5b2143)

Errors in console:
![изображение](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/9ae580c2-0999-4225-a258-0cffa3e7809b)

-----

As for Log, restarted HA with debug logging, will post later.
