### ISSUE TITLE
Make the units less strict?

### ISSUE THREAD

**Issue by dogmatic69** [aukedejong/lovelace-windrose-card#33]
Had an idea to use this card for the [lightning tracker](https://github.com/mrk-its/homeassistant-blitzortung) and it kinda works using the azimuth and distance (in place of speed).

Only issue is "auto" for unit's does not work, and when forcing it the only option is `km/h`. Would be nice if I could use `km` instead. (I'm near the head of the arrow on the lightning map for reference)

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/94674/8f2fd678-0b91-4b21-ab2a-0c2ced569b46)

```

      - type: custom:windrose-card
        title: Lightning
        data_period:
          hours_to_show: 3
        max_width: 400
        refresh_interval: 300
        windspeed_bar_location: bottom
        windspeed_bar_full: false
        wind_direction_entity:
          entity: sensor.blitzortung_lightning_azimuth
          direction_unit: degrees
          use_statistics: false
          direction_compensation: 0
        windspeed_entities:
          - entity: sensor.blitzortung_lightning_distance
            name: Distance
            speed_unit: kph
            use_statistics: false
        output_speed_unit: kph
        speed_range_beaufort: false
        windrose_draw_north_offset: 0
        cardinal_direction_letters: NESW
        matching_strategy: direction-first
        center_calm_percentage: true
        wind_direction_count: 16
        speed_range_step: 10
        speed_range_max: 100
```
