### ISSUE TITLE
1 Hour chart not updating

### ISSUE THREAD

**Issue by LouPaloma** [aukedejong/lovelace-windrose-card#34]
Version 1.2.0 with Hass 2023.6.3, Frontend 20230608.0 - latest

After updating to the `data_period:` with `hours_to_show` value of 1, the chart does not update unless there's a manual refresh of the page.  Even changing the `refresh_interval` to a low number doesn't seem to change the chart.

Here's an example card:

```
- type: custom:windrose-card
  title: Last Hour
  data_period:
    hours_to_show: 1
  max_width: 400
  refresh_interval: 60
  windspeed_bar_location: bottom
  wind_direction_entity: 
    entity: sensor.home_wind_angle
  windspeed_entities:
    - entity: sensor.home_wind_speed
      name: Speed
    - entity: sensor.home_wind_gust
      name: Gusts
  wind_direction_unit: degrees
  #direction_compensation: 0
  speed_range_beaufort: false
  input_speed_unit: mph
  output_speed_unit: mph
  speed_ranges:
    - from_value: 0
      color: rgb(32,174,32)
    - from_value: 3
      color: yellow
    - from_value: 6
      color: orange
    - from_value: 8
      color: red
    - from_value: 10
      color: purple
  #cardinal_direction_letters: NESW
  card_mod:
    class: top-level-card
```
