### ISSUE TITLE
[FR] Console warnings: Speed unavailable at timestamp ... is not a number - can we have a "debug_messages: false" option?

### ISSUE THREAD

**Issue by ildar170975** [aukedejong/lovelace-windrose-card#38]
Console is flooded by these warnings:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/d3048485-e245-4a76-8efe-e3cee6018ab1)

Here I got 140 warnings (+1 is for another card) after just pressing F5.
The card:
```
  - type: custom:windrose-card
    title: Wind direction
    wind_direction_entity:
      entity: sensor.home_gismeteo_wind_bearing
    windspeed_entities:
      - entity: sensor.home_gismeteo_wind_speed
        name: Home
    data_period:
      hours_to_show: 168
```
As far as I understand, that means that during these 168 hours there are 140 occurrences of "unavailable" value for the "speed".
I do admit that this info may be useful - but I think that we should have an option to switch these "debug messages" OFF.
I do not propose to switch off ALL messages - just messages which are not critical (like these ones).

My proposal is:
- add a new `debug_messages` option (`true` / `false`) (default is `true` - but it could be `false` instead);
- this option is to switch on/off only WARNINGS - and probably only SOME of them (less critical).
