### ISSUE TITLE
Card may not be displayed (observed in Edit mode)

### ISSUE THREAD

**Issue by ildar170975** [aukedejong/lovelace-windrose-card#39]
1.2.1
2023.7.0
When a dashboard is in Edit mode, the windrose-card may not be displayed.
This is a very weird issue - please read it carefully.

Code for a view:
```
  - theme: ''
    title: test_panel_1
    path: test_panel_1
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: history-graph
            entities:
              - sun.sun
      - type: custom:windrose-card
        title: Wind direction
        wind_direction_entity:
          entity: sensor.home_gismeteo_wind_bearing
        windspeed_entities:
          - entity: sensor.home_gismeteo_wind_speed
            name: Home
        data_period:
          hours_to_show: 24
```

How the view is supposed to look:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/1fa5a44b-9667-44c4-a450-d3b7448b217c)

The windrose-card in Editor:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/7102a958-b9f5-411d-80ea-718c64145875)

----------------------

And now about the problem:
1. Switch the current dashboard to the Edit mode.
2. Add 2 new cards (history-graph, windrose-card - see a code above).
3. Both cards are displayed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/2e91aabd-5f31-463d-b1cf-04ffdc966cbd)

4. Refresh the page (F5 in Chrome) - the windrose-card is NOT displayed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/284e3238-e95c-462c-aaea-1a53d41ca513)

Pressing F5 does not help.

5. Leave Edit mode - the windrose-card is still NOT dispalyed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/cbf1f3a7-7501-43c9-8b6f-3e8d72b52282)

6. Refresh the page - the windrose card is displayed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/39acb019-ea89-4b0e-8429-7d5efb6f472d)

7. Switch to the Edit mode - the windrose-card is displayed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/45f16b7c-69c3-4cd9-b69e-297ee6928ba9)

8. Refresh the page - - the windrose-card is NOT displayed:

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/4bf924e4-acd2-4547-bf3b-94d8867e18c3)

-----------------------

I see same in Chrome & FF (Win10):

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/36fa06ec-bd52-49c7-8c49-3fe8b4745828)

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/c9cd82b8-6c1a-4b74-a289-d06d5f0ec285)

-----------------

What I managed to see in Code Inspector (Chrome):

![image](https://github.com/aukedejong/lovelace-windrose-card/assets/71872483/6dcb0c3b-22b4-49b3-b556-d9c3445f0267)

---------------

Why "history-graph"?
I realized this config as a minimal working example.
Use "history-graph" w/o "vertical-stack", or place in to the stack "entities card" instead of "history-graph" - then the "windrose-card" is displayed properly...

----------

I do not see the issue in the iOS Companion App (iPad Air 2, iOS 15.x).
