### ISSUE TITLE
Speed unit locked to beaufort

### ISSUE THREAD

**Issue by lienbacher** [aukedejong/lovelace-windrose-card#43]
Since quite a few releases I have noticed my speed unit in the graph is beaufort, despite configured for kph. I just checked the documentation again and was unable to find a mistake in my config. 

<img width="982" alt="image" src="https://github.com/aukedejong/lovelace-windrose-card/assets/37445630/40994b10-d192-407e-9f00-4b99188a8c42">

This is the config in text:
```
type: custom:windrose-card
title: Wind direction
max_width: 400
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.gw1100a_v2_2_1_wind_direction
windspeed_entities:
  - entity: sensor.gw1100a_v2_2_1_wind_speed
    name: Average
    speed_unit: kph
input_speed_unit: kph
output_speed_unit: kph
speed_range_step: 5
speed_range_max: 50
data_period:
  hours_to_show: 168
```
