### ISSUE TITLE
[Feature request] : add the possibility to use weather forecast entity data 

### ISSUE THREAD

**Issue by arnpere** [aukedejong/lovelace-windrose-card#46]
This windrose representation of wind data is awesome to display data from the past.
I believe it would also be very useful to display forecast data is the same way !
For example I'd love to be able to draw data provided by an entity called "weather.{some place}" which returns the following forecast data with 1 hour resolution, starting from now, including wind_bearing & wind speed (JSON format) :

```
temperature: 11.4
temperature_unit: °C
humidity: 90
pressure: 1002.7
pressure_unit: hPa
wind_bearing: 130
wind_speed: 21.6
wind_speed_unit: km/h
visibility_unit: km
precipitation_unit: mm
forecast:
  - datetime: "2023-11-11T21:00:00+00:00"
    condition: rainy
    wind_bearing: 135
    temperature: 11.7
    wind_speed: 21.6
    precipitation: 3.1
    humidity: 95
  - datetime: "2023-11-11T22:00:00+00:00"
    condition: rainy
    wind_bearing: 195
    temperature: 12.5
    wind_speed: 10.8
    precipitation: 1
    humidity: 90
  - datetime: "2023-11-11T23:00:00+00:00"
    condition: rainy
    wind_bearing: 255
    temperature: 13.3
    wind_speed: 21.6
    precipitation: 1
    humidity: 85
  - datetime: "2023-11-12T00:00:00+00:00"
    condition: rainy
    wind_bearing: 270
    temperature: 14.1
    wind_speed: 39.6
    precipitation: 1
    humidity: 85
  - datetime: "2023-11-12T01:00:00+00:00"
    condition: rainy
    wind_bearing: 270
    temperature: 13.9
    wind_speed: 39.6
    precipitation: 0.1
    humidity: 80
  - datetime: "2023-11-12T02:00:00+00:00"
    condition: rainy
    wind_bearing: 270
    temperature: 13.8
    wind_speed: 36
    precipitation: 0.1
    humidity: 80
  - datetime: "2023-11-12T03:00:00+00:00"
    condition: rainy
    wind_bearing: 275
    temperature: 13.7
    wind_speed: 36
    precipitation: 0.1
    humidity: 75
[to be continued]
```
