### ISSUE TITLE
Gust Windspeed Entity not available

### ISSUE THREAD

**Issue by DavidWicks** [aukedejong/lovelace-windrose-card#48]
The graphic in the example shows a vertical bar showing the windspeed gust.

It appears as though this entity setting is not available ?

**Comment by aukedejong** [comment]
Hi David,

Thie gust windspeed in the example uses data from a second windspeed entity.

Below an example configuration:

```
windspeed_entities:
  - entity: sensor.wind_speed
     name: Average
  - entity: sensor.wind_gust_speed
    name: Gust
```

Hope this helps.
