### ISSUE TITLE
Windspeed bar range

### ISSUE THREAD

**Issue by rufik** [aukedejong/lovelace-windrose-card#5]
It would be great to have possibility to define max value for windspeed bar. It looks like 90 km/h is hardcoded maximum with step=10. My max reading value is about 50 km/h, so half of the scale is not use at all. So setting up max to 50 would be best for me (step is 5 then).

**Comment by aukedejong** [comment]
Good idea.  I think adding two configuration options could fix this.
windspeed_bar_max: 20
windspeed_bar_step: 5

With this configuration the bar gets there ranges:
0 - 5
5 - 10
10 - 15
15 - 20
20 - infinity

The unit depends on the output unit configured. Defaults will also depend on the output unit. 
When output unit is Beaufort (the default) an error shown, because Beaufort uses fixed speed ranges.


For now, you can set the windspeed_bar_full options to false.

`windspeed_bar_full: false`

This way the speed ranges that are not used, will not be rendered.

**Comment by aukedejong** [comment]
Released version 0.6.0.
Implemented what I described in my previous comment.

**Comment by rufik** [comment]
Very nice, thanks a lot. I'm going to try it this weekend.

**Comment by srwareham** [comment]
This is great, thank you! Might it be possible to define our own custom steps? The use case for me would be more or less (semi) replicating the Beaufort scale, but in miles per hour. I find it helpful for the legend to show values in mph rather than the Beaufort number, as they're a more familiar unit to me. Relatedly, I'm generally interested in greater resolution at lower mph and less concerned about distinguishing anything above a near gale.

The handy `custom:compass-card` lovelace card uses a configuration where you can define start points for bands. For example, this is the relevant part of the configuration I have
``` yaml

indicator_sensors:
  - sensor: sensor.tempest_st_00086807_wind_direction
    indicator:
      type: arrow_inward
      dynamic_style:
        sensor: sensor.tempest_st_00086807_wind_speed
        bands:
          - from_value: 0
            color: green
          - from_value: 4
            color: yellow
          - from_value: 6
            color: orange
          - from_value: 8
            color: red
          - from_value: 11
            color: purple
```

**Comment by aukedejong** [comment]
Yes, that would be an useful feature.
Also the option to define the colours per speed range.
I'll start working on that.

**Comment by aukedejong** [comment]
Released version 0.7.0

Added speed_ranges configuration. Same style is the compass-card.  There is an example in the readme.

Can you do some tests, see if everything is working as expected.  Thanks.

**Comment by srwareham** [comment]
Thanks!! Testing now. The colors specification works but I 'm seeing something a bit odd with the binning. I tried recreating the beaufort scale using the m/s values used in the code. However, I'm getting different results.
![image](https://user-images.githubusercontent.com/3392952/226215129-a15d03ef-9dfd-4cf9-9f16-3a159eede37e.png)

Stock beaufort scale configuration
``` yaml
type: custom:windrose-card
title: Wind direction (1h)
hours_to_show: 1
max_width: 400
refresh_interval: 360
windspeed_bar_location: bottom
windspeed_bar_full: false
wind_direction_entity: sensor.tempest_st_00086807_wind_bearing
windspeed_entities:
  - entity: sensor.tempest_st_00086807_wind_speed
    name: wind speed
wind_direction_unit: degrees
input_speed_unit: mph
output_speed_unit: bft
windrose_draw_north_offset: 21
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
```

Manually implemented beaufort scale implementation
``` yaml
type: custom:windrose-card
title: Wind direction (1h)
hours_to_show: 1
max_width: 400
refresh_interval: 360
windspeed_bar_location: bottom
windspeed_bar_full: false
wind_direction_entity: sensor.tempest_st_00086807_wind_bearing
windspeed_entities:
  - entity: sensor.tempest_st_00086807_wind_speed
    name: wind speed
wind_direction_unit: degrees
input_speed_unit: mps
output_speed_unit: mps
windrose_draw_north_offset: 21
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
speed_ranges:
  - from_value: 0
    color: blue
  - from_value: 0.3
    color: dodgerblue
  - from_value: 1.6
    color: deepskyblue
  - from_value: 3.4
    color: aqua
  - from_value: 5.5
    color: red
  - from_value: 8
    color: purple

```


I used the m/s thresholds defined in the code: https://github.com/aukedejong/lovelace-windrose-card/blob/9222416552efcd747b491cf50087168124925642/src/WindSpeedConverter.ts#L137-L152
