### ISSUE TITLE
Can you edit and give an example how to get gust scale visible?

### ISSUE THREAD

**Issue by CT2HUU** [aukedejong/lovelace-windrose-card#52]
Can you edit and give an example how to get gust scale visible?
Great card, thanks!

**Comment by aukedejong** [comment]
You need a second entity for the gust  wind speeds.
Add this entity to the windspeed list:

```
windspeed_entities:
  - entity: sensor.wind_speed_average
    name: Average
  - entity: sensor.wind_speed_gust
    name: Gust
```


If this answers your question, please let me know.
