### ISSUE TITLE
`No matching speed found for direction` but data is present and accounted for

### ISSUE THREAD

**Issue by USA-RedDragon** [aukedejong/lovelace-windrose-card#6]
Hello!

I've got the card configured like so:

```
type: custom:windrose-card
title: Wind direction
hours_to_show: 0.3
max_width: 500
refresh_interval: 12
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity: sensor.wind_direction
windspeed_entities:
  - entity: sensor.average_wind
    name: Average
wind_direction_unit: degrees
input_speed_unit: mps
output_speed_unit: mph
direction_compensation: 1
cardinal_direction_letters: NESW
matching_strategy: direction-first
direction_speed_time_diff: 1
```

The console is filled up wlth messages like:

```
No matching speed found for direction 115 at timestamp 1677966836.649485
No matching speed found for direction 323 at timestamp 1677967652.440865
No matching speed found for direction 178 at timestamp 1677967812.34858
No matching speed found for direction 47 at timestamp 1677968036.220359
```

The sensors are mqtt sensors coming from `rtl_433`:
```
mqtt:
  sensor:
    - name: Average Wind
      device_class: wind_speed
      unit_of_measurement: "m/s"
      value_template: "{{ value_json.wind_avg_m_s }}"
      state_topic: rtl_433/Cotech-367959

    - name: Peak Wind
      device_class: wind_speed
      unit_of_measurement: "m/s"
      value_template: "{{ value_json.wind_max_m_s }}"
      state_topic: rtl_433/Cotech-367959

    - name: Wind Direction
      unit_of_measurement: "°"
      state_class: measurement
      value_template: "{{ value_json.wind_dir_deg }}"
      state_topic: rtl_433/Cotech-367959
```

The source data doesn't have any gaps in it (ie: at any given moment, the sensors are never unavailable): 
![Screenshot_History – Home Assistant — Mozilla Firefox_1](https://user-images.githubusercontent.com/13051767/222932336-db8ef502-9e40-4870-b9f3-713edb7ee836.png)
![Screenshot_History – Home Assistant — Mozilla Firefox_2](https://user-images.githubusercontent.com/13051767/222932337-2769e4d9-62a3-402b-a5c2-88728014181f.png)

Any clues why the data is unable to be matched to the speed?
