### ISSUE TITLE
unit always in Beaufort despite kph used

### ISSUE THREAD

**Issue by tparvais** [aukedejong/lovelace-windrose-card#65]
V1.5

windspeed bars are always in beaufort despite unit is set to kph
```
type: custom:windrose-card
title: Rose des Vents
data_period:
  hours_to_show: 24
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: true
wind_direction_entity:
  entity: sensor.anemometre_wind_angle
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.anemometre_vitesse_du_vent
    name: Moyenne
    speed_unit: kph
    use_statistics: false
    render_relative_scale: false
  - entity: sensor.anemometre_gust_strength
    name: Rafale
    speed_unit: kph
    use_statistics: false
    render_relative_scale: false
output_speed_unit: kph
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: direction-first
center_calm_percentage: true
```
![image](https://github.com/user-attachments/assets/b55fa4d7-3dfb-4c9e-9e49-de11591ca8cb)
