### ISSUE TITLE
Windrose-card is killing my Lovelace dashbaord

### ISSUE THREAD

**Issue by deanfourie1** [aukedejong/lovelace-windrose-card#67]
I'm having huge issues with this card and lovelace load speeds. I absolutely love this card and what it brings to my dashboard, but it causing huge issues with Lovelace and the browser often crashes.

It takes about 2 minutes for the card to load and for my entire lovelace dashboard to become stable.

Any ideas?

Thanks

**Comment by aukedejong** [comment]
You can try to use the statistics data or decrease the hours_to_show value.

Not all entities support statistics data, maybe you get an error.

Example for using statistics data:

```
windspeed_entities:
  - entity: sensor.wind_speed
    name: Wind speed
    use_statistics: true
```

Hope this helps, please let me know.
