### ISSUE TITLE
Arrow head not visible on card after configuration

### ISSUE THREAD

**Issue by godfreym29** [aukedejong/lovelace-windrose-card#70]
I've configured the card with "show_current_direction_arrow: true" and it shows on the configuration card, but when I save the configuration the arrow head is not visible on the card.

Have tried clearing the cache, etc.

_Current Config:_

```
type: custom:windrose-card
title: Wind direction (24hr)
data_period:
  hours_to_show: 24
refresh_interval: 300
windspeed_bar_full: false
windspeed_bar_location: right
center_calm_percentage: true
direction_count: 32
show_current_direction_arrow: true
wind_direction_entity:
  entity: sensor.gw2000a_wind_direction
  direction: degrees
  use_statistics: false
windspeed_entities:
  - entity: sensor.gw2000a_wind_speed
    name: Average
    speed_unit: auto
    use_statistics: false
  - entity: sensor.gw2000a_wind_gust
    name: Gusts
    speed_unit: auto
    use_statistics: false
speed_range_beaufort: false
output_speed_unit: mph
matching_strategy: direction-first
colors:
  rose_lines: ''
  rose_direction_letters: ''
  rose_percentages: blue
  rose_current_direction_arrow: red
  bar_border: hsl(200, 100%, 60%)
  bar_unit_name: purple
  bar_name: ''
  bar_unit_values: blue
  bar_percentages: ''
speed_ranges:
  - from_value: 0
    color: rgb(0,128,128)
  - from_value: 1
    color: rgb(0,255,0)
  - from_value: 5
    color: yellow
  - from_value: 10
    color: hsl(200, 100%, 60%)
  - from_value: 20
    color: orange
  - from_value: 40
    color: red

```
