### ISSUE TITLE
Wind direction Variable and Nowind in translation

### ISSUE THREAD

**Issue by seg-on** [aukedejong/lovelace-windrose-card#77]
Hi,
As I wrote before, I am parsing wind direction and speed from the national metological website.
They give 10 value for direction
S - North
SZ - North West
Z - West
JZ - South West
J- South
JV - South East
V - East
SV - Nort East
PREM - Variable
BEZV - No wind

Is it possible to set direction_letters for variable (PREM)?

My current setup is:

```
wind_direction_entity:
  entity: sensor.shmu_pn_smer
  direction_unit: letters
  direction_letters: SVJZX
  use_statistics: false
```
