### ISSUE TITLE
Feature Request - Multiple Speed Ranges

### ISSUE THREAD

**Issue by gedger** [aukedejong/lovelace-windrose-card#93]
I find that it's hard to have a single speed range and step that works with all the variable winds conditions my site has. When showing low speeds, say below 20 mph, then a speed range step of 2.5 is good to show the details, however, when the wind starts to get up then there's too many steps and a step of 5 works better. So my idea is to allow multiple speed ranges. So for the example, if the average speed is 20 or below then use a step size of 2.5, if the average speed is between 21 and 40 then use a step size of 5 etc.

```
Speed_ranges:
  - range: 20
      step: 2.5
  - range: 40
      step: 5
  - range: 60
      step: 10
```
