### ISSUE TITLE
Current wind arrow not using shortest route to next wind direction.

### ISSUE THREAD

**Issue by aukedejong** [aukedejong/lovelace-windrose-card#94]
Love the card. Is there any way to keep the arrow from going all the way around the rose when it goes from something like 350 degrees to 10 degrees? I like having the arrow but it updates every second and when the wind direction is mostly out of the north, it constantly goes all the way around the circle as it transits past 0 degrees.

Thanks Chris for reporting this bug.

**Comment by aukedejong** [comment]
Fixed in version 1.11.3

**Comment by vk2him** [comment]
I've updated to 1.11.3 and after clearing cache the Card is now empty - no errors, it will display a Title if you have one coded but the graphs no longer display
![image](https://github.com/user-attachments/assets/ad95cdb2-409e-45a8-84d3-a85316e96c88)

**Comment by gedger** [comment]
Just tried 1.11.4 I get the blank screen too on Safari 18.0.1. Here's my config.

```
type: custom:windrose-card
data_period:
  hours_to_show: 1
refresh_interval: 300
output_speed_unit_label: mph
windspeed_bar_location: right
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.wind_dir
  direction_unit: degrees
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.wind_speed
    name: speed
    speed_unit: kph
  - entity: sensor.wind_gust_speed
    name: gust
    speed_unit: kph
output_speed_unit: mph
speed_range_beaufort: false
speed_range_step: 2.5
speed_range_max: 45
matching_strategy: direction-first
center_calm_percentage: false
current_direction:
  show_arrow: true
  arrow_size: 60
corner_info:
  top_left:
    label: Current windspeed
    unit: " mph"
    entity: sensor.wind_speed
```

Looking in the javascript console I see this.

```
WR ERROR Error during init: 
Error: Entity sensor.wind_dir not found.
checkEntity — windrose-card.js:35:146215
checkEntities — windrose-card.js:35:145473
refreshCardConfig — windrose-card.js:35:150187
hass — windrose-card.js:35:149959
value — hui-card.ts:99
value — hui-card.ts:40
value — hui-section.ts:67
map
value — hui-section.ts:275
(anonymous function) — hui-section.ts:192
value — hui-section.ts:206
value — hui-section.ts:95
performUpdate — reactive-element.ts:1327
(anonymous function) — reactive-element.ts:1233
```

sensor.wind_dir is definitely OK, dropping back to 1.11.2 and everything works with the same configuration.

**Comment by gedger** [comment]
Dropping back to 1.11.2 I see these messages in Javascript console, so perhaps something not 100% with my configuration?

```
[Log] WR ERROR WindRoseDirigent: render(): Could not render, init or measurements not ready true - false (windrose-card.js, line 34)
[Warning] WR WARN Matching results entity sensor.wind_speed, 1 not matched of total 13 direction measurements (windrose-card.js, line 34)
[Warning] WR WARN Matching results entity sensor.wind_gust_speed, 1 not matched of total 13 direction measurements (windrose-card.js, line 34)
```

**Comment by aukedejong** [comment]
What version of HA are you running?
I changed the entity config checking. Maybe I use something that wasn't available in older versions.

**Comment by gedger** [comment]
```
Core 2024.10.3
Frontend 20241002.3
```

**Comment by vk2him** [comment]
Here's my config

```
type: custom:windrose-card
data_period:
  hours_to_show: 1
max_width: 400
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.weatherdisplay_wind_degrees
  direction_unit: degrees
  use_statistics: false
  direction_compensation: 0
corner_info:
  top_left:
    label: Current windspeed
    unit: " kph"
    entity: sensor.weatherdisplay_wind_speed
  top_right:
    label: Wind direction
    unit: °
    color: red
    entity: sensor.weatherdisplay_wind_degrees
windspeed_entities:
  - entity: sensor.weatherdisplay_wind_speed
    name: Wind Speed
    speed_unit: kph
    use_statistics: false
colors:
  rose_current_direction_arrow: orange
output_speed_unit: kph
speed_range_beaufort: false
windrose_draw_north_offset: 0
cardinal_direction_letters: NESW
matching_strategy: speed-first
center_calm_percentage: false
current_direction:
  show_arrow: true
```

I get this in console

```
windrose-card.js?hac…ag=5912706961113:35 WR ERROR Error during init:  Error: Entity sensor.weatherdisplay_wind_degrees not found.
    at rr.checkEntity (windrose-card.js?hac…706961113:35:146203)
    at rr.checkEntities (windrose-card.js?hac…706961113:35:145459)
    at ar.refreshCardConfig (windrose-card.js?hac…706961113:35:150171)
    at set hass (windrose-card.js?hac…706961113:35:149939)
    at i.value (hui-card.ts:99:21)
    at HTMLElement.<anonymous> (hui-card.ts:125:14)
    at n (fire_event.ts:76:8)
    at create-element-base.ts:198:5
```

The sensor.weatherdisplay_wind_degrees is fine and I'm using it in other cards/sensors

![image](https://github.com/user-attachments/assets/5ea667dc-e9fe-46ec-8711-4c4d737252ac)
