### ISSUE TITLE
Wind direction / direction arrow /

### ISSUE THREAD

**Issue by matomatusov** [aukedejong/lovelace-windrose-card#95]
I will try to set up a windrose card.
I don't see the wind direction ("arrow") on the Windrose diagram.
Don't know what the problem might be?

![Windrose](https://github.com/user-attachments/assets/5d68d848-3d85-487a-a3b1-fb923637537c)

My card settings:

```
type: custom:windrose-card
title: Wind direction
data_period:
  hours_to_show: 48
refresh_interval: 300
windspeed_bar_location: bottom
windspeed_bar_full: false
wind_direction_entity:
  entity: sensor.iakovi2_wind_direction_cardinal
  use_statistics: false
  direction_compensation: 0
windspeed_entities:
  - entity: sensor.iakovi2_wind_speed
    name: Speed
  - entity: sensor.iakovi2_wind_gust
    name: Guset
    speed_unit: auto
    use_statistics: true
speed_range_beaufort: true
windrose_draw_north_offset: 0
current_direction:
  show_arrow: true
  arrow_size: 50
  center_circle_size: 30
compass_direction:
  auto_rotate: false
  entity: sensor.iakovi2_wind_direction_degrees
cardinal_direction_letters: North,East,South,West
matching_strategy: direction-first
center_calm_percentage: true
corner_info:
  top_left:
    label: Current windspeed
    unit: " km/h"
    entity: sensor.iakovi2_wind_gust
  top_right:
    label: Wind direction
    unit: °
    color: red
    entity: sensor.iakovi2_wind_direction_degrees
  bottom_left:
    label: Compass
    unit: °
    entity: sensor.iakovi2_wind_direction_cardinal

```

Thanks
